title:               "#hystericalanduseless"
url:                 https://daily.hystericalanduseless.club
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Moria
  url:               flanintheface.com/@rosenkreuzer
  email:             rosenkreuzer@hystericalanduseless.club

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist